---
:project: foreman
:releases:
  :1.10.0:
    :redmine_release_id: 63
:repos:
  :foreman:
    :main: true
    :branch: 1.10-stable
    :repo: https://github.com/theforeman/foreman.git
  :smart-proxy:
    :main: true
    :branch: 1.10-stable
    :repo: https://github.com/theforeman/smart-proxy.git
  :foreman-selinux:
    :main: true
    :branch: 1.10-stable
    :repo: https://github.com/theforeman/foreman-selinux.git
  :foreman-installer:
    :main: true
    :branch: 1.10-stable
    :repo: https://github.com/theforeman/foreman-installer.git
:ignores:
